### ISSUE TITLE
[Test] Move CI to Jenkins and run end-to-end tests for every change

### ISSUE THREAD

**Issue by rafaelsbz** [pazuzu-io/pazuzu#154]
- Move CI to a Jenkins Pull Request Job
- Create end to end tests that actually create a Docker Container and run some bats tests against it

**Comment by rafaelsbz** [comment]
I've created https://pazuzu.ci.zalan.do/job/pazuzu-proto/23/console where I'm running 'go get' and 'go test' on master. I'll iterate on it to create a Pull Request Job that runs on branches

**Comment by rafaelsbz** [comment]
An update on the state of things:

### End to end tests:
There's still work to do. Running the bats tests for containers depends on fixing issue #132. Also, it would be a good idea to write some bats tests for pazuzu itself.

### Pull Request Job:
https://pazuzu.ci.zalan.do/job/pazuzu-pull-request-proto/

The pull request job is up and running. As of now, it fetches the PR, builds, runs go test, installs pazuzu and runs pazuzu --version to check if it actually installs.

The tests from #160 that involve a live pazuzu-registry are being skipped since this job doesn't actually run a pazuzu-registry. 

**Important**: This job is **silent** and doesn't post anything to Github. This is by design, and this behaviour was implemented based on the following comment: https://github.com/jenkinsci/ghprb-plugin/issues/407#issuecomment-248668043
The silent behaviour was put in place in order to avoid having pazuzu PRs depending on closed infrastructure from Zalando, since external contributors would have no access to Jenkins. It also prevents private information from Zalando from leaking through Jenkins logs. 

 
### Prototype job and integrated tests with the registry
This link has the prototype Jenkins job where I wrote some experiments with integration:
https://pazuzu.ci.zalan.do/job/pazuzu-proto/ 

It's based on the script from the PR Job, but updated to try and run the registry tests from #160. For that, it's necessary to have a pazuzu-registry running on localhost:8080. The Prototype Job should clone and run an instance of pazuzu-registry to get this done. 


**The state of things here is**: the script clones and starts pazuzu-registry in background, waits one minute and then starts pazuzu tests. The times are usually right but, even so, the tests can't really connect to the registry. This is still under investigation.

There are also a couple of things that can be improved on the test itself, which are described in #167. The main improvement here would be removing the hacky 1 minute wait time.

**Comment by rafaelsbz** [comment]
Marked as help wanted as I need to hand it over to someone.

**Comment by netme** [comment]
@rafaelsbz could you please clarify the status?

**Comment by rafaelsbz** [comment]
I'll remove myself as assignee since I'm not able to work on this as much (my team is Swamped). 

The status is pretty much the same as my last post: 
- Pull Request jobs runs unit tests. 
- There's a prototype job with an attempt to run the tests that integrate with registry, but I wasn't able to make pazuzu and registry talk because of limitations on port 8080.
