### ISSUE TITLE
Add LICENSE file to pazuzu registry

### ISSUE THREAD

**Issue by netme** [pazuzu-io/pazuzu#170]

**Comment by kinshuk4** [comment]
@netme - should I move this issue to pazuzu-registry instead and start working on it? And do we have some license format ready?

**Comment by netme** [comment]
@kinshuk4 

> should I move this issue to pazuzu-registry instead and start working on it?

Sure

>  And do we have some license format ready?

I'm pretty sure we have it, but I don't know where exactly. Please sync with OpenSource Guild or @pgronkiewicz

**Comment by fehmicansaglam** [comment]
There is already a LICENCE file in pazuzu-registry but it is not present in pazuzu. I guess that just the issue title is wrong.

**Comment by netme** [comment]
Can be, or the issue was not closed :-)
